CREATE SCHEMA "event" AUTHORIZATION postgres;

CREATE TABLE "event"."event" (
	event_id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	event_desc varchar(255) NULL,
	end_time timestamp NULL,
	event_notification bool NULL,
	event_name varchar(255) NULL,
	start_time timestamp NULL,
	CONSTRAINT event_pkey PRIMARY KEY (event_id)
);